# Generated by Django 5.0.6 on 2024-06-24 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 8, 58, 30, 440817), verbose_name='qo`shilgan vaqti'),
        ),
    ]
