# Generated by Django 5.0.6 on 2024-06-24 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_joined_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 9, 50, 22, 360231), verbose_name='qo`shilgan vaqti'),
        ),
    ]
